package com.manager.entity;

// Generated 2017-7-14 16:34:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Tblbom generated by hbm2java
 */
public class Bom implements java.io.Serializable {

	private BomId id;
	private String topName;
	private String partName;
	private String FName;
	private Integer secq;
	private Double useQty;
	private String editor;
	private Date datetime;

	public Bom() {
	}

	public Bom(BomId id, String partName) {
		this.id = id;
		this.partName = partName;
	}

	public Bom(BomId id, String topName, String partName, String FName,
			Integer secq, Double useQty, String editor, Date datetime) {
		this.id = id;
		this.topName = topName;
		this.partName = partName;
		this.FName = FName;
		this.secq = secq;
		this.useQty = useQty;
		this.editor = editor;
		this.datetime = datetime;
	}

	public BomId getId() {
		return this.id;
	}

	public void setId(BomId id) {
		this.id = id;
	}

	public String getTopName() {
		return this.topName;
	}

	public void setTopName(String topName) {
		this.topName = topName;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public Integer getSecq() {
		return this.secq;
	}

	public void setSecq(Integer secq) {
		this.secq = secq;
	}

	public Double getUseQty() {
		return this.useQty;
	}

	public void setUseQty(Double useQty) {
		this.useQty = useQty;
	}

	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
