package com.manager.entity;

// Generated 2017-7-14 16:34:52 by Hibernate Tools 3.4.0.CR1

/**
 * TblbomId generated by hbm2java
 */
public class BomId implements java.io.Serializable {

	private String topPartnumber;
	private String FPartnumber;
	private String partNumber;

	public BomId() {
	}

	public BomId(String topPartnumber, String FPartnumber, String partNumber) {
		this.topPartnumber = topPartnumber;
		this.FPartnumber = FPartnumber;
		this.partNumber = partNumber;
	}

	public String getTopPartnumber() {
		return this.topPartnumber;
	}

	public void setTopPartnumber(String topPartnumber) {
		this.topPartnumber = topPartnumber;
	}

	public String getFPartnumber() {
		return this.FPartnumber;
	}

	public void setFPartnumber(String FPartnumber) {
		this.FPartnumber = FPartnumber;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BomId))
			return false;
		BomId castOther = (BomId) other;

		return ((this.getTopPartnumber() == castOther.getTopPartnumber()) || (this
				.getTopPartnumber() != null
				&& castOther.getTopPartnumber() != null && this
				.getTopPartnumber().equals(castOther.getTopPartnumber())))
				&& ((this.getFPartnumber() == castOther.getFPartnumber()) || (this
						.getFPartnumber() != null
						&& castOther.getFPartnumber() != null && this
						.getFPartnumber().equals(castOther.getFPartnumber())))
				&& ((this.getPartNumber() == castOther.getPartNumber()) || (this
						.getPartNumber() != null
						&& castOther.getPartNumber() != null && this
						.getPartNumber().equals(castOther.getPartNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTopPartnumber() == null ? 0 : this.getTopPartnumber()
						.hashCode());
		result = 37
				* result
				+ (getFPartnumber() == null ? 0 : this.getFPartnumber()
						.hashCode());
		result = 37
				* result
				+ (getPartNumber() == null ? 0 : this.getPartNumber()
						.hashCode());
		return result;
	}

}
