package com.manager.entity;

// Generated 2017-7-14 16:34:52 by Hibernate Tools 3.4.0.CR1

/**
 * TblbomId generated by hbm2java
 */
public class BomId implements java.io.Serializable {

	private String topPartnumber;
	private String f_Partnumber;
	private String partNumber;

	public BomId() {
	}




	public String getF_Partnumber() {
		return f_Partnumber;
	}




	public void setF_Partnumber(String f_Partnumber) {
		this.f_Partnumber = f_Partnumber;
	}




	public String getTopPartnumber() {
		return this.topPartnumber;
	}

	public void setTopPartnumber(String topPartnumber) {
		this.topPartnumber = topPartnumber;
	}

	public String getPartNumber() {
		return this.partNumber;
	}

	public void setPartNumber(String partNumber) {
		this.partNumber = partNumber;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return super.toString();
	}




	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((f_Partnumber == null) ? 0 : f_Partnumber.hashCode());
		result = prime * result + ((partNumber == null) ? 0 : partNumber.hashCode());
		result = prime * result + ((topPartnumber == null) ? 0 : topPartnumber.hashCode());
		return result;
	}




	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BomId other = (BomId) obj;
		if (f_Partnumber == null) {
			if (other.f_Partnumber != null)
				return false;
		} else if (!f_Partnumber.equals(other.f_Partnumber))
			return false;
		if (partNumber == null) {
			if (other.partNumber != null)
				return false;
		} else if (!partNumber.equals(other.partNumber))
			return false;
		if (topPartnumber == null) {
			if (other.topPartnumber != null)
				return false;
		} else if (!topPartnumber.equals(other.topPartnumber))
			return false;
		return true;
	}




	public BomId(String topPartnumber, String f_Partnumber, String partNumber) {
		super();
		this.topPartnumber = topPartnumber;
		this.f_Partnumber = f_Partnumber;
		this.partNumber = partNumber;
	}







}
