package com.manager.entity;

import java.math.BigDecimal;

// Generated 2017-7-13 17:04:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Tblinvlog generated by hbm2java
 */
public class Invlog implements java.io.Serializable {

	private int id;
	private String partnumber;
	private String partName;
	private String partRev;
	private String supplierName;
	private String partUnit;
	private BigDecimal qty;
	private String MIo;
	private String orderNumber;
	private String editor;
	private Date datetime;

	public Invlog() {
	}

	public Invlog(int id, String partnumber, String partRev,
			String supplierName) {
		this.id = id;
		this.partnumber = partnumber;
		this.partRev = partRev;
		this.supplierName = supplierName;
	}

	public Invlog(int id, String partnumber, String partName,
			String partRev, String supplierName, String partUnit, BigDecimal qty,
			String MIo, String orderNumber, String editor, Date datetime) {
		this.id = id;
		this.partnumber = partnumber;
		this.partName = partName;
		this.partRev = partRev;
		this.supplierName = supplierName;
		this.partUnit = partUnit;
		this.qty = qty;
		this.MIo = MIo;
		this.orderNumber = orderNumber;
		this.editor = editor;
		this.datetime = datetime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPartnumber() {
		return this.partnumber;
	}

	public void setPartnumber(String partnumber) {
		this.partnumber = partnumber;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getPartRev() {
		return this.partRev;
	}

	public void setPartRev(String partRev) {
		this.partRev = partRev;
	}

	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getPartUnit() {
		return this.partUnit;
	}

	public void setPartUnit(String partUnit) {
		this.partUnit = partUnit;
	}

	public BigDecimal getQty() {
		return qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	public String getMIo() {
		return this.MIo;
	}

	public void setMIo(String MIo) {
		this.MIo = MIo;
	}

	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}
}
